pipeline {
    agent any

    tools {
        maven 'Maven-Local'   // Name of Maven installation in Jenkins
        jdk 'JDK-17'          // Name of JDK installation in Jenkins
    }

    stages {
        stage('Checkout SCM') {
            steps {
                // Checkout code from GitHub
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                // Run Maven in the directory where pom.xml exists
                dir('SeleniumAutomationFramework') {  // your project folder
                    bat 'mvn clean test'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}
