url = https://katalon-demo-cura.herokuapp.com
username = John Doe
password = ThisIsNotAPassword
error_message= Login failed! Please ensure the username and password are valid.
facility= Tokyo CURA Healthcare Center
readmission = true
program = Medicare
visitDateDay = 10
visitDateMonthYear = October 2026
comment = Regular checkup